config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
	#root "gossips#index"
	resources :gossips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def sanitize_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:address])
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

	def index
		@gossips = Gossip.all
	end

	def new
	end

	def create
		@gossip = Gossip.new(gossip_params)
		@gossip.save

		if @gossip.save
	    redirect_to @gossip
	  else
		   render 'new'
		 end		
	end

  def show
    @gossip = Gossip.find(params[:id])
  end

 	def edit
	  @id = Gossip.find(params[:id])
	end

	def update
	  @gossip = Gossip.find(params[:id])
	 
	  if @gossip.update(gossip_params)
	    redirect_to @gossip
	  else
	    render 'edit'
	  end
	end

	def destroy
		@gossip = Gossip.find(params[:id])
		@gossip.destroy
		redirect_to gossips_path
	end



private
  def gossip_params
    params.permit(:anonymous_author, :content)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/gossips/edit.html.erb
<h1> Modifie ton gossip </h1>

<%= form_tag gossip_path(@id), method: :put do%>

<p>
	<%= label_tag "content", "Your little secret" %>
	<%= text_field_tag "content" %>
</p>

<p>
	<%= submit_tag "Modifier la rumeur" %>
</p>

<% end %>

<p> <%= link_to "THP GOSSIPS", gossips_path %></p>

app/views/gossips/index.html.erb
<h1>THP GOSSIPS</h1>

<table>

	<tr>
		<td><em> Glorieux Auteur</em></td>
		<td><em> Glorieux Contenu </em></td>
		<td>voir</td>
		<td>supprimer</td>
	</tr>


<% @gossips.each do |gossip| %>

	<tr>
		<td><%= gossip.anonymous_author %></td>
		<td><%= gossip.content %></td>
		<td><%= link_to "voir", gossip_path(gossip)%></td>
		<td><%= link_to 'Supprimer', gossip_path(gossip),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
	</tr>
<% end %>
</table>
<p> <%= link_to "Nouvelle rumeur", new_gossip_path%></p>
<p> <%= link_to "Retour au profile", new_user_session_path%></p>

app/views/gossips/new.html.erb
<h1> Nouveau gossip </h1>

<%= form_tag (gossips_path) do%>

<p>
	<%= label_tag "anonymous_author", "Pseudo" %>
	<%= text_field_tag "anonymous_author" %>

</p>

<p>
	<%= label_tag "content", "Your little secret" %>
	<%= text_field_tag "content" %>
</p>

<p>
	<%= submit_tag "Nouvelle rumeur" %>
</p>

<% end %>



<p> <%= link_to "THP GOSSIPS", gossips_path %></p>

app/views/gossips/show.html.erb
<h1> Ton Gossip </h1>

<p> <%= @gossip.anonymous_author %></p>
<p> <%= @gossip.content %></p>
<p> <%= link_to "Modifier", edit_gossip_path %></p>
<p> <%= link_to "THP GOSSIPS", gossips_path %></p>
<p> <%= link_to 'Supprimer', @gossip,
              method: :delete,
              data: { confirm: 'Are you sure?' } %></p>

app/views/home/index.html.erb
<h1>My Home!</h1>

<ul>
  <% if user_signed_in? %>
    <li>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    </li>
    <li>
      <%= current_user.email %>
    </li>
    <li>
      <%= link_to "Edit Account", edit_user_registration_path %>
    </li>
    <li>
      <%= link_to "Gossips", gossips_path %>
    </li>
  <% else %>
  <li>
    <%= link_to "Sign In", new_user_session_path %>
  </li>
  <li>
    <%= link_to "Sign Up", new_user_registration_path %>
  </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>